# Generated by Django 4.0.1 on 2022-01-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220106_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lipiuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
